### ISSUE TITLE
Exception when searching for words together with a field defined with ext_method

### ISSUE THREAD

**Issue by tstrachota** [wvanbergen/scoped_search#174]
Scoped search raises an exception when searching for words together with a field defined with ext_method:

```
scoped_search :on => :custom_flag, :complete_value => { :true => true, :false => false }, :ext_method => :search_by_custom_flag
```

A query `some word, custom_flag = true` resutls in:
```
2018-03-07T12:42:20 27901054 [app] [E] ActiveModel::UnknownAttributeError: unknown attribute 'custom_flag' for Class.
 | /home/vagrant/foreman/scoped_search/lib/scoped_search/definition.rb:116:in `column'
 | /home/vagrant/foreman/scoped_search/lib/scoped_search/definition.rb:123:in `type'
 | /home/vagrant/foreman/scoped_search/lib/scoped_search/definition.rb:254:in `block in default_fields_for'
 | /home/vagrant/foreman/scoped_search/lib/scoped_search/definition.rb:254:in `select'
 | /home/vagrant/foreman/scoped_search/lib/scoped_search/definition.rb:254:in `default_fields_for'
 | /home/vagrant/foreman/scoped_search/lib/scoped_search/query_builder.rb:437:in `to_sql'
 | /home/vagrant/foreman/scoped_search/lib/scoped_search/query_builder.rb:529:in `block in to_sql'
 | /home/vagrant/foreman/scoped_search/lib/scoped_search/query_builder.rb:529:in `map'
 | /home/vagrant/foreman/scoped_search/lib/scoped_search/query_builder.rb:529:in `to_sql'
 | /home/vagrant/foreman/scoped_search/lib/scoped_search/query_builder.rb:54:in `build_find_params'
 | /home/vagrant/foreman/scoped_search/lib/scoped_search/query_builder.rb:22:in `build_query'
 | /home/vagrant/foreman/scoped_search/lib/scoped_search/definition.rb:300:in `block in register_named_scope!'
```

**Comment by tstrachota** [comment]
PR: https://github.com/wvanbergen/scoped_search/pull/175
